---
version: "3"
services:
  db:
    build: ./Docker-db
    container_name: devopsdb1
    ports:
      - "1111:3306"
  webapp:
    build: ./Docker-app
    container_name: devopsapp1
    ports:
      - "5555:8080"
    depends_on:
     - db
